#!/bin/sh
# $Id: cc-compile-dl 2909 2007-12-12 21:21:47Z m0 $

if [ $# -lt 1 ]
then
  echo "usage: source" 1>&2
  exit 1
fi

CC_DLFLAG=`head -n 1 conf-dlflag`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-dlflag" 1>&2
  exit 1
fi

exec ./cc-compile $1 ${CC_DLFLAG}
