#!/bin/sh

fatal()
{
  echo "cc-compile-dl: fatal: $1" 1>&2
  exit 1
}

if [ $# -lt 1 ]
then
  echo "cc-compile-dl: usage: [@dir] source" 1>&2
  exit 1
fi

#
# check if new base dir was specified
#

BASE_DIR="."
if [ $# -eq 2 ]
then
  BASE_DIR=`echo "$1" | sed 's/^@//g'`
  shift
fi

CC_DLFLAG=`head -n 1 "${BASE_DIR}/conf-dlflag"`
if [ $? -ne 0 ]
then
  fatal "could not read ${BASE_DIR}/conf-dlflag"
fi

exec "${BASE_DIR}/cc-compile" $1 ${CC_DLFLAG}
