#!/bin/sh

if [ $# -lt 2 ]
then
  echo "usage: basename objects ..." 1>&2
  exit 1
fi

LD_TYPE=`head -n 1 conf-ldtype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-ldtype" 1>&2
  exit 1
fi
LD=`head -n 1 conf-ld`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-ld" 1>&2
  exit 1
fi
SYS_TYPE=`head -n 1 conf-systype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-systype" 1>&2
  exit 1
fi
SO_SUFFIX=`head -n 1 conf-sosuffix`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-sosuffix" 1>&2
  exit 1
fi

main="$1"
shift

# read in optional flag files
if [ -f "${main}.lff" ]
then
  for f in `cat "${main}.lff"`
  do
    targ="`dirname $main`/`dirname $f`/`basename $f`"
    FLAGS="`cat $targ 2>/dev/null`"
    LDFLAGS="${LDFLAGS} ${FLAGS}"
  done
fi

# library name
libname=`./mk-libname "${main}"`
if [ $? -ne 0 ]
then
  echo "fatal: could not execute ./mk-libname" 1>&2
  exit 1
fi

# major version number
if [ -f ${main}.vmj ]
then
  VMJ=`head -n 1 ${main}.vmj 2>/dev/null`
  if [ $? -ne 0 ]
  then
    echo "fatal: could not read ${main}.vmj" 1>&2
    exit 1
  fi
fi

# minor version number
if [ -f ${main}.vmn ]
then
  VMN=`head -n 1 ${main}.vmn 2>/dev/null`
  if [ $? -ne 0 ]
  then
    echo "fatal: could not read ${main}.vmn" 1>&2
    exit 1
  fi
fi

rm -f "${libname}"

case "${LD_TYPE}" in
  GCC)
    case "${SYS_TYPE}" in
      DARWIN)
        if [ ! -z ${vmj} ]
        then
          if [ ! -z ${vmn} ]
          then
            ver="${vmj}.${vmn}.0"
          else
            ver="${vmj}.0.0"
          fi
        else
          ver="1.0.0"
        fi
        release=`uname -r | awk -F. '{print $1}'`
        if [ ${release} -gt 7 ]
        then
          ${LD} -dynamiclib \
                -current_version "${ver}" \
                -install_name "${libname}" \
                -o "${libname}" ${1+"$@"} ${LDFLAGS}
        else
          libtool -dynamic \
            -current_version "${ver}" \
            -install_name "${libname}" \
            -o "${libname}" ${1+"$@"} ${LDFLAGS} -lc
        fi
        ;;
      SUNOS)
        ld -G -z text -o "${libname}" ${1+"$@"} ${LDFLAGS} -lc
        ;;
      MS_WINDOWS)
        ${LD} -shared -o "${libname}" ${1+"$@"} ${LDFLAGS}
        ;;
      *)
        ${LD} -shared -Wl,-soname,"${libname}" -o "${libname}" ${1+"$@"} ${LDFLAGS} -lc
        ;;
    esac
    ;;
  HP_C)
    ${LD} -b -o "${libname}" ${1+"$@"} ${LDFLAGS}
    ;;
  COMPAQ_C)
    ${LD} -no_archive -shared -o "${libname}" ${1+"$@"} ${LDFLAGS}
    ;;
  INTEL)
    ${LD} -shared -o "${libname}" ${1+"$@"} ${LDFLAGS}
    ;;
  SUN_C)
    ${LD} -G -z text -o "${libname}" ${1+"$@"} ${LDFLAGS}
    ;;
  MIPSPRO)
    ${LD} -shared -soname "${libname}" -o "${libname}" ${1+"$@"} ${LDFLAGS}
    ;;
  *)
    echo "fatal: unknown compiler - cannot produce shared objects" 1>&2
    exit 1
    ;;
esac

if [ $? -ne 0 ]
then
  exit 1
fi
echo "${libname}" >> "${main}".vlb
