#!/bin/sh

#
# Print additional compiler flags necessary to compile object files that
# can be used for shared libraries.
#

if [ -f conf-x-cctype ]
then
  CC_TYPE=`head -n 1 conf-x-cctype`
  if [ $? -ne 0 ]
  then
    echo "fatal: could not read conf-x-cctype" 1>&2
    exit 1
  fi
  SYS_TYPE=`head -n 1 conf-x-systype`
  if [ $? -ne 0 ]
  then
    echo "fatal: could not read conf-x-systype" 1>&2
    exit 1
  fi
else
  CC_TYPE=`head -n 1 conf-cctype`
  if [ $? -ne 0 ]
  then
    echo "fatal: could not read conf-cctype" 1>&2
    exit 1
  fi
  SYS_TYPE=`head -n 1 conf-systype`
  if [ $? -ne 0 ]
  then
    echo "fatal: could not read conf-systype" 1>&2
    exit 1
  fi
fi

case "${CC_TYPE}" in
  GCC)
    case "${SYS_TYPE}" in
      DARWIN)
        echo '-dynamic'
        ;;
      MS_WINDOWS)
        ;;
      *)
        echo '-fPIC'
        ;;
    esac
    ;;
  HP_C)
    echo '+Z'
    ;;
  COMPAQ_C)
    echo '-shared'
    ;;
  INTEL)
    echo '-fpic'
    ;;
  SUN_C)
    # obsolete on SPARC? manual says -xcode=pic32 but this fails on x86
    echo '-KPIC'
    ;;
  MIPSPRO)
    echo '-KPIC'
    ;;
  *)
    echo 'fatal: unknown compiler - cannot print dynamic library flags' 1>&2
    exit 1
    ;;
esac
