#!/bin/sh

fatal()
{
  echo "mk-libname: fatal: $1" 1>&2
  exit 1
}

if [ $# -lt 1 ]
then
  echo "mk-libname: usage: basename" 1>&2
  exit 1
fi

#
# check if base directory was specified
#

BASE_DIR="."
echo "$1" | grep '^@' 2>&1 >/dev/null
if [ $? -eq 0 ]
then
  BASE_DIR=`echo $1 | sed 's/^@//g'`
  shift
fi

SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
if [ $? -ne 0 ]
then
  fatal "could not read ${BASE_DIR}/conf-systype"
fi
SO_SUFFIX=`head -n 1 "${BASE_DIR}/conf-sosuffix"`
if [ $? -ne 0 ]
then
  fatal "could not read ${BASE_DIR}/conf-sosuffix"
fi

main="$1"
shift

vmj=`head -n 1 ${main}.vmj 2>/dev/null`
vmn=`head -n 1 ${main}.vmn 2>/dev/null`

if [ "x${vmj}" != "x" ]
then
  if [ "x${vmn}" != "x" ]
  then
    case "${SYS_TYPE}" in
      MS_WINDOWS)
        exec echo ${main}.${SO_SUFFIX}
        ;;
      DARWIN)
        exec echo ${main}.${vmj}.${vmn}.${SO_SUFFIX}
        ;;
      *)
        exec echo ${main}.${SO_SUFFIX}.${vmj}.${vmn}
        ;;
    esac
  else
    case "${SYS_TYPE}" in
      MS_WINDOWS)
        exec echo ${main}.${SO_SUFFIX}
        ;;
      DARWIN)
        exec echo ${main}.${vmj}.${SO_SUFFIX}
        ;;
      *)
        exec echo ${main}.${SO_SUFFIX}.${vmj}
        ;;
    esac
  fi
else
  exec echo ${main}.${SO_SUFFIX}
fi
