#!/bin/sh

PROGRAM_NAME="mk-libname"

warning()
{
  echo "${PROGRAM_NAME}: warn: $1" 1>&2
}

error()
{
  echo "${PROGRAM_NAME}: error: $1" 1>&2
}

fatal()
{
  echo "${PROGRAM_NAME}: fatal: $1" 1>&2
  exit 1
}

if [ $# -lt 1 ]
then
  echo "${PROGRAM_NAME}: usage: basename" 1>&2
  exit 1
fi

#
# check if base directory was specified
#

BASE_DIR="."
echo "$1" | grep '^@' 2>&1 >/dev/null
if [ $? -eq 0 ]
then
  BASE_DIR=`echo $1 | sed 's/^@//g'`
  shift
fi

#
# Assume cross-compilation if cross compilation tools are
# defined.
#

if [ -f "${BASE_DIR}/conf-x-cc" ]
then
  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-x-systype"
  fi
else
  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-systype"
  fi
fi

SO_SUFFIX=`head -n 1 "${BASE_DIR}/conf-sosuffix"`
if [ $? -ne 0 ]
then
  fatal "could not read ${BASE_DIR}/conf-sosuffix"
fi

main="$1"
shift

VERSION_MAJOR=`head -n 1 ${main}.vmj 2>/dev/null`
VERSION_MINOR=`head -n 1 ${main}.vmn 2>/dev/null`

if [ ! -z "${VERSION_MAJOR}" ]
then
  if [ ! -z "${VERSION_MINOR}" ]
  then
    case "${SYS_TYPE}" in
      MS_WINDOWS)
        exec echo ${main}.${SO_SUFFIX}
        ;;
      DARWIN)
        exec echo ${main}.${VERSION_MAJOR}.${VERSION_MINOR}.${SO_SUFFIX}
        ;;
      *)
        exec echo ${main}.${SO_SUFFIX}.${VERSION_MAJOR}.${VERSION_MINOR}
        ;;
    esac
  else
    case "${SYS_TYPE}" in
      MS_WINDOWS)
        exec echo ${main}.${SO_SUFFIX}
        ;;
      DARWIN)
        exec echo ${main}.${VERSION_MAJOR}.${SO_SUFFIX}
        ;;
      *)
        exec echo ${main}.${SO_SUFFIX}.${VERSION_MAJOR}
        ;;
    esac
  fi
else
  exec echo ${main}.${SO_SUFFIX}
fi
