#!/bin/sh

CC_TYPE=`head -n 1 conf-cctype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-cctype" 1>&2
  exit 1
fi
SYS_TYPE=`head -n 1 conf-systype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-systype" 1>&2
  exit 1
fi


case "${CC_TYPE}" in
  GCC)
    case "${SYS_TYPE}" in
      MS_WINDOWS)
        ;;
      *)
        echo '-fPIC'
        ;;
    esac
    ;;
  HP_C)
    echo '+Z'
    ;;
  COMPAQ_C)
    echo '-shared'
    ;;
  INTEL)
    echo '-fpic'
    ;;
  SUN_C)
    # obsolete on SPARC? manual says -xcode=pic32 but this fails on x86
    echo '-KPIC'
    ;;
  MIPSPRO)
    echo '-KPIC'
    ;;
  *)
    echo 'fatal: unknown compiler - cannot print PIC flag' 1>&2
    exit 1
    ;;
esac
